## This is just a test file for the embeddning

In [2]:
from pprint import pprint as print
from gensim.models.fasttext import FastText
from gensim.test.utils import datapath

In [3]:
# i cannot find a good bin file for this...
#from gensim.models.fasttext import load_facebook_model
#wv = load_facebook_model()


corpus_file = datapath('lee_background.cor')  # absolute path to corpus
model3 = FastText(vector_size=4, window=3, min_count=1)
model3.build_vocab(corpus_file=corpus_file)  # scan over corpus to build the vocabulary
total_words = model3.corpus_total_words  # number of words in the corpus
model3.train(corpus_file=corpus_file, total_words=total_words, epochs=5)

(240956, 301935)

In [4]:
from gensim.test.utils import get_tmpfile
from gensim.test.utils import common_texts

model = FastText(vector_size=4, window=3, min_count=1)  # instantiate
model.build_vocab(corpus_iterable=common_texts)
model.train(corpus_iterable=common_texts, total_examples=len(common_texts), epochs=10)
print(model.corpus_total_words)

fname = get_tmpfile("fasttext.model")
model.save(fname)
model = FastText.load(fname)

print(model.corpus_total_words)

29
29


In [5]:
import numpy as np

'computer' in model.wv.key_to_index  # New word, currently out of vocab

True

In [8]:


old_vector = np.copy(model.wv['computer'])  # Grab the existing vector

old_vector

new_sentences = [
    ['computer', 'aided', 'design'],
    ['computer', 'science'],
    ['computational', 'complexity'],
    ['military', 'supercomputer'],
    ['central', 'processing', 'unit'],
    ['onboard', 'car', 'computer'],
]


In [9]:
model.build_vocab(new_sentences, update=True)  # Update the vocabulary
model.train(new_sentences, total_examples=len(new_sentences), epochs=model.epochs)

new_vector = model.wv['computer']
new_vector

array([-0.00263242, -0.03817195, -0.02007434,  0.00741351], dtype=float32)

In [10]:
np.allclose(old_vector, new_vector, atol=1e-4)  # Vector has changed, model has learnt something



True

In [ ]:
'computer' in fb_model.wv.key_to_index  # New word, currently out of vocab
False
old_computer = np.copy(fb_model.wv['computer'])  # Calculate current vectors
fb_model.build_vocab(new_sentences, update=True)
fb_model.train(new_sentences, total_examples=len(new_sentences), epochs=model.epochs)
new_computer = fb_model.wv['computer']
np.allclose(old_computer, new_computer, atol=1e-4)  # Vector has changed, model has learnt something
False
'computer' in fb_model.wv.key_to_index  # New word is now in the vocabulary
True

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [22]:
from gensim.models.fasttext import load_facebook_model
import numpy as np

new_sentences = [
    ['computer', 'aided', 'design'],
    ['computer', 'science'],
    ['computational', 'complexity'],
    ['military', 'supercomputer'],
    ['central', 'processing', 'unit'],
    ['onboard', 'car', 'computer'],
]
cap_path = datapath("crime-and-punishment.bin")



fb_model = load_facebook_model(cap_path)



In [41]:
'' in fb_model.wv.key_to_index

False

In [24]:
old_computer = np.copy(fb_model.wv['computer'])
old_computer

array([-0.01754012,  0.05520927,  0.06355207,  0.05296071,  0.05046377],
      dtype=float32)

In [25]:
fb_model.build_vocab(new_sentences, update=True)
fb_model.train(new_sentences, total_examples=len(new_sentences), epochs=fb_model.epochs)
new_computer = fb_model.wv['computer']
new_computer

array([-0.02225105,  0.06033591,  0.06490689,  0.05112575,  0.05164139],
      dtype=float32)

In [26]:
np.allclose(old_computer, new_computer, atol=1e-4)  # Vector has changed, model has learnt something

False

In [27]:
'computer' in fb_model.wv.key_to_index  # New word is now in the vocabulary

True

In [33]:
similarities = fb_model.wv.most_similar('computation')
similarities


[('computational', 0.9919778108596802),
 ('complexity', 0.9892442226409912),
 ('лгать,', 0.9892262816429138),
 ('обыденную', 0.9888888001441956),
 ('supercomputer', 0.9874089360237122),
 ('ashamed.', 0.9848596453666687),
 ('приставания', 0.981712818145752),
 ('время,', 0.97895348072052),
 ('lodged', 0.9770848751068115),
 ('угрозы,', 0.9761002659797668)]

In [37]:
similarities = model.wv.most_similar_cosmul('computation')

similarities


[('computer', 0.9239985346794128),
 ('interface', 0.8864936828613281),
 ('eps', 0.8393409848213196),
 ('minors', 0.7720398902893066),
 ('time', 0.7128621339797974),
 ('human', 0.6134594082832336),
 ('system', 0.4492993950843811),
 ('graph', 0.4410752058029175),
 ('user', 0.3536098897457123),
 ('trees', 0.2776937782764435)]

In [38]:
not_matching = model.wv.doesnt_match("human computer interface tree".split())

not_matching


'tree'

In [39]:
sim_score = model.wv.similarity('computer', 'human')
sim_score

0.05815026

In [40]:
sim_score = model.wv.similarity('computer', 'computation')
sim_score

0.84799886